# Generated by Django 3.2.3 on 2021-07-23 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelml', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelml',
            name='modelml_url',
            field=models.FileField(upload_to=''),
        ),
    ]
