# Generated by Django 3.2.3 on 2021-08-09 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelml', '0002_alter_modelml_modelml_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelml',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='modelml',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
