# Generated by Django 3.2.3 on 2021-09-07 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelml', '0005_auto_20210828_1350'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalModelstat',
            fields=[
                ('userid', models.CharField(db_column='userID', max_length=100, primary_key=True, serialize=False)),
                ('modelid', models.CharField(blank=True, db_column='modelID', max_length=100, null=True)),
                ('baseid', models.CharField(blank=True, db_column='baseID', max_length=100, null=True)),
                ('modelname', models.CharField(blank=True, db_column='modelName', max_length=100, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('training_starttime', models.DateField(blank=True, null=True)),
                ('training_endtime', models.DateField(blank=True, null=True)),
                ('statistics_tp', models.FloatField(blank=True, null=True)),
                ('statistics_fp', models.FloatField(blank=True, null=True)),
                ('statistics_tn', models.FloatField(blank=True, null=True)),
                ('statistics_fn', models.FloatField(blank=True, null=True)),
                ('statistics_f1', models.FloatField(blank=True, null=True)),
                ('statistics_precision', models.FloatField(blank=True, null=True)),
                ('statistics_recall', models.FloatField(blank=True, null=True)),
                ('statistics_train_acc', models.FloatField(blank=True, null=True)),
                ('statistics_train_loss', models.FloatField(blank=True, null=True)),
                ('statistics_test_acc', models.FloatField(blank=True, null=True)),
                ('statistics_test_loss', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'local_modelstat',
                'managed': False,
            },
        ),
    ]
