# Generated by Django 3.2.3 on 2021-09-08 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('modelml', '0007_auto_20210907_1416'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelml',
            old_name='base_model',
            new_name='baseline_ID',
        ),
        migrations.RemoveField(
            model_name='modelml',
            name='description',
        ),
        migrations.RemoveField(
            model_name='modelml',
            name='modelml_url',
        ),
        migrations.RemoveField(
            model_name='modelml',
            name='title',
        ),
        migrations.AddField(
            model_name='modelml',
            name='model_ID',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='modelml',
            name='model_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Modeldefault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255, null=True)),
                ('modelml_url', models.FileField(upload_to='')),
                ('base_model', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(max_length=100, null=True)),
                ('model_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
