# Generated by Django 3.2.3 on 2021-09-13 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelml', '0008_auto_20210908_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelml',
            name='training_endtime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modelml',
            name='training_starttime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
