# Generated by Django 3.2.3 on 2021-09-22 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelml', '0009_auto_20210913_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelml',
            name='accuracy_image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='modelml',
            name='loss_image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
