# Generated by Django 3.2.3 on 2021-09-22 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelml', '0010_auto_20210922_0506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelml',
            name='accuracy_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='modelml',
            name='loss_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
