# Generated by Django 3.2.3 on 2021-09-24 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelml', '0011_auto_20210922_0814'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelml',
            name='csv',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
