# Generated by Django 3.2.3 on 2021-07-26 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('API_quota', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='API_usage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='package',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user.package'),
        ),
    ]
