# Generated by Django 3.2.3 on 2021-09-03 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_alter_user_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.EmailField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
    ]
