# Generated by Django 3.2.3 on 2021-09-07 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_auto_20210903_0301'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='TF_quota',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='company',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
