# Generated by Django 3.2.3 on 2021-09-07 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_auto_20210907_0801'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='TF_usage',
            field=models.IntegerField(default=0),
        ),
    ]
