# Generated by Django 3.2.3 on 2022-01-27 05:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_user_tf_usage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForgotPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('Expires', models.DateTimeField(default=datetime.datetime(2022, 1, 27, 6, 8, 5, 902606, tzinfo=utc))),
            ],
        ),
    ]
