# Generated by Django 3.2.3 on 2022-01-28 13:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_forgotpassword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forgotpassword',
            name='Expires',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 28, 13, 17, 50, 442759, tzinfo=utc)),
        ),
    ]
