# Generated by Django 3.2.3 on 2022-01-28 13:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_alter_forgotpassword_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forgotpassword',
            name='Expires',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 28, 13, 31, 27, 937784, tzinfo=utc)),
        ),
    ]
