# Generated by Django 3.2.3 on 2022-01-29 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_alter_forgotpassword_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forgotpassword',
            name='Expires',
            field=models.DateTimeField(),
        ),
    ]
