# Generated by Django 3.2.3 on 2022-02-14 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_auto_20220214_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Getting_Started',
            field=models.IntegerField(default=1),
        ),
    ]
