# Generated by Django 3.2.3 on 2022-02-14 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_alter_user_getting_started'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Getting_Started',
            field=models.BooleanField(default=True),
        ),
    ]
