# Generated by Django 3.2.3 on 2022-02-17 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_alter_user_getting_started'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Getting_Started',
            new_name='started_detail',
        ),
        migrations.AddField(
            model_name='user',
            name='started_home',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='started_test',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='started_train',
            field=models.BooleanField(default=True),
        ),
    ]
